#ifndef APPLICATION_APP_BOOTLOADER_INC_APP_BOOTLOADER_HOST_H_
#define APPLICATION_APP_BOOTLOADER_INC_APP_BOOTLOADER_HOST_H_

#include <stdint.h>


#endif /* APPLICATION_APP_BOOTLOADER_INC_APP_BOOTLOADER_HOST_H_ */